name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-1  # Ensure each artifact has a unique name
          path: ./build/

      - name: Upload additional artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-2  # Ensure each artifact has a unique name
          path: ./additional-files/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifact-1

      - name: Download additional artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifact-2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
